### ISSUE TITLE
커스텀 plug-in개발을 위한 API 참조 문서가 필요합니다./API reference documentation for custom plug-in development is required.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking-plugins#24]
## Description
plug-in개발을 위한 참조 문서가 없는 것 같습니다. 커스텀 plug-in의 개발 혹은 기존 개발된 plug-in의 커스터마이징등을 위해서는 관련 내용이 정리된 문서가 필요합니다. 문서 제작 부탁드립니다.

There seems to be no reference documentation for plug-in development. In order to develop a custom plug-in or to customize an existing plug-in, a document with related contents is required. Please create a document.

**Comment by WoodNeck** [comment]
Good, I'll create one when I have time for it :)
