### ISSUE TITLE
Pagination의 type값중 'scroll'을 'bullet'으로 변경하고 scroll에 대한 추가 옵션을 지정하는 방식으로 변경하면 좋을 것 같습니다./It would be good to change 'scroll' to 'bullet' among the type values of pagination and change it to specify additional options for scroll.

### ISSUE THREAD

**Issue by hiuny** [naver/egjs-flicking-plugins#25]
## Description
type값 중 `bullet`과 `fraction`은 UI의 형태를 구분하여 지어진 이름인데 반해, `scroll`은 형태가 아닌 기능 일부('bullet' 타입인데 bullet 몇 개만 표시, 패널 index에 따라 bullet 컨테이너를 스크롤함)에 초점이 맞춰진 이름이므로 `bullet` 타입의 세부 옵션으로 정의되는 것이 좀 더 자연스러운 것 같아 보입니다.  예시 코드는 **_코드1_** 을 참조 부탁드립니다.

---

Among the type values, `bullet` and `fraction` are names that distinguish the shape of the UI, whereas `scroll` is a part of a function rather than a shape ('bullet' type, but only a few bullets are displayed, and the bullet container is scrolled according to the panel index) ), so it seems more natural to be defined as a detailed option of type `bullet`. For example code, please refer to **_Code 1_**.

**_코드1_** - `bullet` 타입의 추가 파라미터 정의 예시  
**_Code 1_** - Example of defining additional parameters of `bullet` type
```javascript
new Pagination({
  type: 'bullet',
  param: {
    // 표시할 bullet 개수. 생략시 전체 표시. 전체 값보다 클 수 없고, 0이하 값 지정시 bullet 비표시
    display: 5,
     // bullet의 형태를 결정하는 값. A, B는 임의로 지정한 값이며 해당 bullet형태를 더 잘 설명하는 단어로 대체될 수 있으며 필요시 새로운 타입의 정의도 가능합니다.
    // 'A': 현재 Pagination bullet 데모와 동일한 형태. 중간 index일 때만 display 개수 노출 보장. 처음과 끝 부분에선 한 두개가 적을 수 있음
    // 'B': 항상 display 개수 만큼의 노출을 보장. 중간 index일 때는 항상 1번 5번 bullet이 작게 표시됨. 처음과 끝일 때는 각각 최우측과 최좌측 bullet이 작게 표시됨
    shape: 'A'
  },
});
```

**스크린샷1** - Pagination 생성자의 type 옵션  
**Screenshot 1** - type option in Pagination constructor
<kbd>![image](https://user-images.githubusercontent.com/2697067/130726363-f4f8b3d1-2738-48c6-a12f-3a1326fd1f6f.png)</kbd>

**Comment by WoodNeck** [comment]
Thanks for the suggestion! I'll discuss it with our team.
