### ISSUE TITLE
Auto play plugin broken with the new update for Vue 3

### ISSUE THREAD

**Issue by megasanjay** [naver/egjs-flicking-plugins#26]
## Description
After the recent Vue3 update, it renders pretty well on my side with the latest version of Vue. However, the autoplay plugin for this instance only does one tick before it stops. i don't see any console errors so I'm assuming it is something with this plugin for Vue3. 

## Steps to check or reproduce
Attaching a codesandbox template that I replicated the issue on. 
https://codesandbox.io/s/holy-morning-5otoz?file=/src/App.vue

**Comment by WoodNeck** [comment]
Hello @megasanjay!
I've found out that AutoPlay is broken while I'm fixing the https://github.com/naver/egjs-flicking/pull/523
So basically it requires Flicking to be updated to fix this issue.
I'll do it asap :)

**Comment by WoodNeck** [comment]
Fixed this issue in Flicking v4.2.5, please try that :)
