### ISSUE TITLE
Pagination bullet is not showing 

### ISSUE THREAD

**Issue by minnsane** [naver/egjs-flicking-plugins#27]
## Description

**Version I use :**
"@egjs/flicking-plugins": "^4.2.1",
"@egjs/ngx-flicking": "^4.3.0",

I tried the pagination plugin as described in the document, but it is not rendered.
I found that DOM has been created, but the height is 0, and the font-size of each bullet is 0 as well.
However, when I set the type as "fraction", it worked just fine.

**Comment by WoodNeck** [comment]
Hello @minnsane!
Did you import the CSS file for the plugin?
Like, as you're using the Angular
```js
@Component({
  templateUrl: './demo.component.html',
  styleUrls: [
    "../node_modules/@egjs/flicking-plugins/dist/pagination.css"
  ]
})
```
