### ISSUE TITLE
Export plugin option interfaces?

### ISSUE THREAD

**Issue by eirikove** [naver/egjs-flicking-plugins#30]
## Description

Not an issue, more of a suggestion for ease-of-access and maintainability. 

For reference, my use-case is that I'm making a Vue3+TS single-file "Carousel" component, and I want to control the `<Flicking>` component's `plugins` prop, with props for my `<Carousel>`

```jsx
// <script setup lang="ts">
import { defineProps, computed, PropType } from "vue";
// What I want to do:
// import { Pagination, PaginationOptions, Arrow, ArrowOptions, ... } from "@egjs/flicking-plugins";

// What I'm doing:
// interface PaginationOptions  {
//    parentEl: HTMLElement | null, 
//    ...copy everything from the PaginationOptions in this repo
// }
// interface ArrowOptions { ... }
// interface FadeArguments { ... }
// and so on


const props = defineProps({
  pagination: { type: Object as PropType<Partial<PaginationOptions> | null>, default: null },
  // same idea for arrows, autoplay, fade, parallax, sync
});
const plugins = computed(() => {
  return [ 
    props.pagination && new Pagination(props.pagination),
    // props.arrow && new Arrow(props.arrow), and so on
   ];
})
```
so that I can instantiate my `Carousel` component like this
```html
<!-- Use default Pagination plugin options -->
<Carousel :pagination="{}">

<!-- Don't use the Pagination plugin-->
<Carousel>

<!-- Use Pagination plugin and overwrite some default pagination options -->
<Carousel :pagination="{ type: 'fraction' }">
```

**Comment by WoodNeck** [comment]
Hello @eirikove!
Thanks for the suggestion, I'd love to add that :)
I'll work on it soon, but in the meantime, you can try using `ConstructorParameters` of Typescript.

```ts
type PaginationOptions = Required<NonNullable<ConstructorParameters<typeof Pagination>[0]>>;
```

That literally has the same type definition of PaginationOptions

**Comment by eirikove** [comment]
> I'll work on it soon, but in the meantime, you can try using `ConstructorParameters` of Typescript.


@WoodNeck Thanks! Good tip! Didn't know that was a thing. 😁
