### ISSUE TITLE
Errors occur in the Sync.spec.ts file after running the npm run test.

### ISSUE THREAD

**Issue by gusrb3164** [naver/egjs-flicking-plugins#36]
## Description

I forked the 4.2.2 version, and install node_modules and execute npm run test. Then Two tests failed.

![failed errors](https://user-images.githubusercontent.com/34272561/153756920-91a2353b-3532-4022-abeb-5a6276b4edda.png)
![error details](https://user-images.githubusercontent.com/34272561/153757179-4dff8972-7e2d-40a8-bb98-a92f7671609a.png)

## Steps to check or reproduce

1. Fork the version of 4.2.2
2. npm install and npm run test
3. npm run test is fail.

**Comment by WoodNeck** [comment]
Hello @gusrb3164!
Please describe which env you're using.
Can you try v4.2.3? It doesn't fail in my env.

![image](https://user-images.githubusercontent.com/26213435/153806357-2ebee365-7d51-4389-92ac-deabb600580c.png)

**Comment by gusrb3164** [comment]
Thank you @WoodNeck!

I changed v4.2.3 and the errors posted earlier have been resolved.

But I got another error. 

My env is node 14.15.4, latest Chrome Desktop version ,MacBook Air (M1, 2020)

![image](https://user-images.githubusercontent.com/34272561/153857306-8d932390-6039-4319-9c85-3830da334b8e.png)

**Comment by WoodNeck** [comment]
I found the cause, please check the comment in PR(#37)
