### ISSUE TITLE
AutoPlay 플러그인 관련 질문

### ISSUE THREAD

**Issue by Siihyun** [naver/egjs-flicking-plugins#42]
## Description

안녕하세요. [AutoPlay](https://naver.github.io/egjs-flicking/Plugins#options) 플러그인을 사용하던 중 궁금한 점이 생겨 질문 드립니다.
duration은 애니메이션에서 해당 탭이 유지되는 시간이라고 이해했는데요.
혹시 다음 탭까지 이동하는데에 걸리는 시간(speed)를 조절할 수 있는 parameter가 있을까요?

감사합니다.

**Comment by malangfox** [comment]
안녕하세요 @Siihyun 님.

패널에서 다음 패널까지 이동하는 애니메이션에 걸리는 시간은 Flicking의 [duration](https://naver.github.io/egjs-flicking/Options#duration) 옵션을 통해 설정하실 수 있습니다.
해당 옵션을 AutoPlay 플러그인과 함께 적용하여 [데모](https://codepen.io/malangfox/pen/oNyxzvB)를 만들어보았으며, 문의를 남겨주신 내용에 해당되는지 획인하여보시고 추가적으로 궁금하신 부분이 있다면 코멘트를 남겨주세요.

**Comment by Siihyun** [comment]
@malangfox 님, 안녕하세요!
빠른 회신 감사드립니다! 

말씀주신 내용이 문의에 해당하는 내용이 맞습니다. duration option 적용하여 해결할 수 있었습니다.
감사합니다 :)

issue는 self-close 하도록 하겠습니다.
좋은 하루 보내세요 🙇‍♂️

**Comment by malangfox** [comment]
현재는 duration 옵션이 사용자 제스쳐로 패널을 넘길 때와 Flicking 내부적으로 패널을 넘길 때 애니메이션에 공통적으로 적용되고 있지만, 남겨주신 이슈에 기반하여 AutoPlay 플러그인을 통해 패널이 넘어갈 때의 애니메이션 시간을 따로 정의할 수 있도록 플러그인에도 관련 옵션을 추가하여보겠습니다.

만약 사용자 제스쳐로 패널이 넘어갈 때와 AutoPlay로 패널을 넘길 때의 애니메이션 시간이 서로 다른 경우가 필요하시다면 이후 버전에서 추가될 옵션을 이용하여보시면 좋겠습니다.

좋은 하루 되세요 :)
