### ISSUE TITLE
Pause autoplay animation on hover

### ISSUE THREAD

**Issue by aniplayIt** [naver/egjs-flicking-plugins#52]
## Description
I'm trying to reach a marquee effect. My configuration is working fine and smooth. The only issue I encountered is when I hover the slider it gets paused correctly but only when it reaches the next slide, aka I would like to have the possibility to interrupt the animation while slide is actually changing. In the video below you can see the behaviour of the bottom slider (flicking) and the top slider (another library - splidejs -):

https://github.com/naver/egjs-flicking-plugins/assets/100148780/28d1b491-502d-4049-a9d3-4d7a197e6d91

I would like to have the same pause behaviour of the top slider. Also this Splide plugin has some performance issues so I would like to switch to flicking if possible.

## Steps to check or reproduce
Svelte
```
import Flicking, { FlickingPanel } from '@egjs/svelte-flicking';
import { AutoPlay } from '@egjs/flicking-plugins';
import '@egjs/svelte-flicking/dist/flicking.css';

let flicking: Flicking;
const plugins = [
	new AutoPlay({ duration: 0, animationDuration: 3000, direction: 'NEXT', stopOnHover: true })
];

<Flicking
	bind:this={flicking}
	{plugins}
	hideBeforeInit={true}
	firstPanelSize="16rem"
	options={{
		align: 'center',
		circular: true,
		easing: (x) => x,
                interruptable: true,
		autoResize: true,
		moveType: 'freeScroll'
	}}
>
	{#each slides as slide, i}
		<FlickingPanel class="h-36 !w-64 !mb-8">
			CONTENT
		</FlickingPanel>
	{/each}
</Flicking>
```

**Comment by aniplayIt** [comment]
I add that slightly moving the slider does exactly what I want - since I have the interruptable and freescroll options -, the only issue is on hover:

https://github.com/naver/egjs-flicking-plugins/assets/100148780/e74c4058-b4f3-495f-8074-36360cf6f938

**Comment by malangfox** [comment]
Hello @aniplayIt.

First, we would like to check the behavior you want.

We have created a [demo](https://codepen.io/malangfox/pen/yLQwOXz) similar to the example you left, which moves the `freeScroll` slide like a marquee effect.

You are welcome to use this implementation as is, but if possible we would like to improve our plugin to support this implementation.

Can we check if this implementation above is the implementation you want?

**Comment by malangfox** [comment]
Since there is no further comment, we will close the issue.
